configfile: "config/config.yaml"


include: "rules/common.smk"
include: "rules/processing.smk"
include: "rules/plotting.smk"
include: "rules/testing.smk"


rule all:
    input:
        collect(
            "results/plots/{dataset}/bootstrap_{type}.html",
            dataset=config["datasets"],
            type=["histograms"],
        ),
        collect(
            "results/plots/{dataset}/distributions_{mode}_effects.html",
            dataset=config["datasets"],
            mode=["all", "selected"],
        )