datasets:
  fig_1b_ft3:
    path: config/data/fig_1b_ft3.tsv
    vars:
      - genotype
      - diet
    value: free T3 serum concentration / pg/mL
    order:
      genotype:
        - WT
        - hepTRbKO
      diet:
        - LDC
        - EtOH
        - LDC+T3
        - EtOH+T3

n_bootstraps: 1000
seed: 214612