datasets:
  fig_1b_ft3:
    path: config/data/fig_1b_ft3.tsv
    comparisons_path: config/comp/fig_1b_ft3.tsv
    vars:
      - genotype
      - diet
    axis: genotype
    color: diet 

comparisons:
  - group_a:
      genotype: WT
      diet: LDC


n_bootstraps: 1000