datasets:
  fig_1b_ft3:
    path: config/data/test.tsv
    vars:
      - var0
      - var1
    value: some measurement
    order:
      var0:
        - a
        - b
      var1:
        - a
        - b

n_bootstraps: 1000
seed: 214612