datasets:
  fig_1b_ft3:
    data: config/data/test.tsv
    variables:
      - var0
      - var1
    value: some measurement
    order:
      var0:
        - a
        - b
      var1:
        - a
        - b
    # optional: restrict comparisons to a subset of the variables
    # comparisons: config/comparisons/something.tsv

min_fold_change: 1.0
n_bootstraps: 1000
seed: 214612
# consider using color blind friendly colors like https://personal.sron.nl/~pault/#sec:qualitative
# or https://mikemol.github.io/technique/colorblind/2018/02/11/color-safe-palette.html
color_scheme: ["#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7"]